package com.mystipixel.royalitems;

import org.bukkit.Material;

import java.io.File;
import java.io.IOException;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;

/**
 * Writes a comprehensive, clean catalog of every dressable vanilla item, grouped into by-type files
 * ({@code weapons}, {@code tools}, {@code armor}, {@code food}, {@code building}, {@code redstone},
 * {@code decoration}, {@code materials}, {@code misc}). Each entry is schema-v2 minimal — the key is the
 * {@code item_id} and material, {@code rarity} drives the border/name/footer and {@code category} is the
 * grey descriptor line; the name and lore auto-generate. Run with {@code /royalitems export}, review the
 * files under {@code catalog-export/}, then move the ones you want into {@code items/}.
 */
final class CatalogExporter {

    private CatalogExporter() {
    }

    /**
     * Ids that live in the hand-tuned {@code 0-overrides.yml} (fuel + bespoke prestige items). The export
     * skips them so the generated catalog never fights those overrides with a duplicate id.
     */
    private static final Set<String> OVERRIDDEN = Set.of(
            "coal", "golden_apple", "enchanted_golden_apple", "nether_star", "elytra", "totem_of_undying",
            "heart_of_the_sea", "beacon", "conduit", "netherite_ingot", "ancient_debris", "dragon_egg",
            "experience_bottle");

    /** One classified bucket for a material: which file it lands in, its descriptor, and its rarity. */
    private record Bucket(String file, String category, String rarity) {
    }

    /** Classify every dressable material and write one YAML file per bucket into {@code dir}. Returns count. */
    static int export(FormattedItemService service, File dir) throws IOException {
        Files.createDirectories(dir.toPath());
        Map<String, StringBuilder> files = new TreeMap<>();
        Map<String, Integer> counts = new TreeMap<>();

        for (Material material : Material.values()) {
            if (!service.isDressable(material)) {
                continue;
            }
            String id = material.name().toLowerCase(Locale.ROOT);
            if (OVERRIDDEN.contains(id)) {
                continue;   // owned by 0-overrides.yml
            }
            Bucket bucket = classify(material);
            StringBuilder body = files.computeIfAbsent(bucket.file, CatalogExporter::header);
            body.append("  ").append(id).append(":\n");
            if (!bucket.rarity.equals("common")) {
                body.append("    rarity: ").append(bucket.rarity).append('\n');
            }
            body.append("    category: \"").append(bucket.category).append("\"\n");
            counts.merge(bucket.file, 1, Integer::sum);
        }

        int total = 0;
        for (Map.Entry<String, StringBuilder> entry : files.entrySet()) {
            File out = new File(dir, entry.getKey() + ".yml");
            try (Writer w = Files.newBufferedWriter(out.toPath(), StandardCharsets.UTF_8)) {
                w.write(entry.getValue().toString());
            }
            total += counts.getOrDefault(entry.getKey(), 0);
        }
        return total;
    }

    private static StringBuilder header(String file) {
        return new StringBuilder()
                .append("# RoyalItems — ").append(file).append(" catalog (generated by /royalitems export).\n")
                .append("# The key is the item_id AND the material; rarity drives the border, name colour and\n")
                .append("# footer; category is the grey descriptor line. Name and lore auto-generate — add\n")
                .append("# name:/lore: only to customise. Rarity is omitted when it is 'common'.\n\n")
                .append("formatted-items:\n\n");
    }

    // ---------------------------------------------------------------- classification

    private static Bucket classify(Material m) {
        String n = m.name();

        if (n.endsWith("_HELMET") || n.endsWith("_CHESTPLATE") || n.endsWith("_LEGGINGS") || n.endsWith("_BOOTS")
                || n.equals("ELYTRA") || n.endsWith("_HORSE_ARMOR") || n.equals("WOLF_ARMOR")) {
            return new Bucket("armor", armorLabel(n), gearRarity(n));
        }
        if (n.endsWith("_SWORD") || n.equals("BOW") || n.equals("CROSSBOW") || n.equals("TRIDENT")
                || n.equals("MACE")) {
            String category = n.endsWith("_SWORD") ? "Sword" : title(n);
            String rarity = n.endsWith("_SWORD") ? gearRarity(n) : (n.equals("MACE") ? "epic" : "uncommon");
            return new Bucket("weapons", category, rarity);
        }
        if (n.endsWith("_PICKAXE") || n.endsWith("_AXE") || n.endsWith("_SHOVEL") || n.endsWith("_HOE")
                || matches(n, "SHEARS", "FISHING_ROD", "FLINT_AND_STEEL", "BRUSH", "SPYGLASS", "SHIELD",
                "COMPASS", "RECOVERY_COMPASS", "CLOCK", "LEAD", "NAME_TAG", "BUCKET")) {
            return new Bucket("tools", toolLabel(n), n.endsWith("_HOE") || n.endsWith("_PICKAXE")
                    || n.endsWith("_AXE") || n.endsWith("_SHOVEL") ? gearRarity(n) : "uncommon");
        }
        if (m.isEdible()) {
            return new Bucket("food", "Food", "common");
        }
        if (isRedstone(n)) {
            return new Bucket("redstone", "Redstone", "uncommon");
        }
        if (isDecoration(n)) {
            return new Bucket("decoration", "Decoration", "common");
        }
        if (m.isBlock()) {
            return new Bucket("building", "Block", "common");
        }
        return new Bucket("materials", "Collection Item", materialRarity(n));
    }

    /** Tier rarity for tools, weapons and armour by their material prefix. */
    private static String gearRarity(String n) {
        if (n.startsWith("NETHERITE")) return "epic";
        if (n.startsWith("DIAMOND") || n.startsWith("TURTLE")) return "rare";
        if (n.startsWith("IRON") || n.startsWith("GOLDEN") || n.startsWith("CHAINMAIL")) return "uncommon";
        return "common"; // wooden, stone, leather, and anything unprefixed
    }

    /** Rarity for raw materials, ingots and gems by the metal/gem in the name. */
    private static String materialRarity(String n) {
        if (n.startsWith("NETHERITE")) return "epic";
        if (n.contains("ECHO") || n.contains("DIAMOND") || n.contains("EMERALD")) return "rare";
        if (n.contains("IRON") || n.contains("GOLD") || n.contains("COPPER") || n.contains("AMETHYST")
                || n.contains("LAPIS") || n.contains("QUARTZ")) return "uncommon";
        return "common";
    }

    private static String armorLabel(String n) {
        if (n.endsWith("_HELMET") || n.equals("TURTLE_HELMET")) return "Helmet";
        if (n.endsWith("_CHESTPLATE")) return "Chestplate";
        if (n.endsWith("_LEGGINGS")) return "Leggings";
        if (n.endsWith("_BOOTS")) return "Boots";
        if (n.equals("ELYTRA")) return "Elytra";
        return "Armor";
    }

    private static String toolLabel(String n) {
        if (n.endsWith("_PICKAXE")) return "Pickaxe";
        if (n.endsWith("_AXE")) return "Axe";
        if (n.endsWith("_SHOVEL")) return "Shovel";
        if (n.endsWith("_HOE")) return "Hoe";
        return title(n);
    }

    private static boolean isRedstone(String n) {
        return matches(n, "REDSTONE", "REDSTONE_TORCH", "REDSTONE_BLOCK", "REDSTONE_LAMP", "REPEATER",
                "COMPARATOR", "PISTON", "STICKY_PISTON", "OBSERVER", "DISPENSER", "DROPPER", "HOPPER",
                "TARGET", "LEVER", "TRIPWIRE_HOOK", "DAYLIGHT_DETECTOR", "NOTE_BLOCK", "BELL")
                || n.endsWith("_RAIL") || n.endsWith("_BUTTON") || n.endsWith("_PRESSURE_PLATE")
                || n.equals("RAIL");
    }

    private static boolean isDecoration(String n) {
        return n.endsWith("_BED") || n.endsWith("_CARPET") || n.endsWith("_CANDLE") || n.equals("CANDLE")
                || n.endsWith("_BANNER") || n.equals("PAINTING") || n.equals("ITEM_FRAME")
                || n.equals("GLOW_ITEM_FRAME") || n.equals("FLOWER_POT") || n.endsWith("_HEAD")
                || n.endsWith("_SKULL") || n.equals("ARMOR_STAND") || n.equals("LANTERN")
                || n.equals("SOUL_LANTERN") || n.equals("TORCH") || n.equals("SOUL_TORCH")
                || n.endsWith("_HANGING_SIGN") || n.endsWith("_SIGN") || n.endsWith("_POTTERY_SHERD")
                || matches(n, "DANDELION", "POPPY", "BLUE_ORCHID", "ALLIUM", "AZURE_BLUET", "CORNFLOWER",
                "OXEYE_DAISY", "LILY_OF_THE_VALLEY", "SUNFLOWER", "LILAC", "ROSE_BUSH", "PEONY",
                "TORCHFLOWER", "WITHER_ROSE", "PITCHER_PLANT");
    }

    private static boolean matches(String name, String... any) {
        for (String a : any) {
            if (name.equals(a)) {
                return true;
            }
        }
        return false;
    }

    /** Title-case a material name: {@code DIAMOND_SWORD} → {@code Diamond Sword}. */
    private static String title(String raw) {
        StringBuilder sb = new StringBuilder();
        for (String word : raw.toLowerCase(Locale.ROOT).split("_")) {
            if (word.isEmpty()) {
                continue;
            }
            if (sb.length() > 0) {
                sb.append(' ');
            }
            sb.append(Character.toUpperCase(word.charAt(0))).append(word.substring(1));
        }
        return sb.toString();
    }
}
